
version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - auth
      - credential

  auth:
    build: ./services/auth
    env_file: .env

  credential:
    build: ./services/credential
    env_file: .env

  fraud:
    build: ./services/fraud
    env_file: .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: uvi

  redis:
    image: redis:7
